// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission05.Models;

namespace Mission05.Migrations
{
    [DbContext(typeof(MovieSubmissionContext))]
    [Migration("20220203030130_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission05.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Horror"
                        });
                });

            modelBuilder.Entity("Mission05.Models.MovieSubmission", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "An amazing film",
                            Rating = "R",
                            Title = "Prisoners",
                            Year = 2013
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 1,
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "Another amazing film",
                            Rating = "R",
                            Title = "Sicario",
                            Year = 2015
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Director = "Denis Villeneuve",
                            Edited = false,
                            LentTo = "",
                            Notes = "An amazing alien film",
                            Rating = "R",
                            Title = "Arrival",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("Mission05.Models.MovieSubmission", b =>
                {
                    b.HasOne("Mission05.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
